"""initial FingerprintHub schema

Revision ID: 0001_init
Revises:
Create Date: 2026-06-30

Schema for the shared image-fingerprint service. Consumers authenticate with
per-key hashes and contribute/sync perceptual-hash fingerprints. A monotonic
``sync_seq`` (advanced on content changes, not on stats-only updates) drives
incremental, tombstone-capable sync.
"""

from __future__ import annotations

from alembic import op


revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS consumers (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            TEXT NOT NULL UNIQUE,
            api_key_hash    TEXT NOT NULL UNIQUE,
            scopes          TEXT[] NOT NULL DEFAULT '{}',
            enabled         BOOLEAN NOT NULL DEFAULT TRUE,
            created_at_ms   BIGINT NOT NULL,
            last_seen_at_ms BIGINT,
            CONSTRAINT chk_consumers_scopes
                CHECK (scopes <@ ARRAY['read','write','admin']::text[])
        )
        """
    )

    # Monotonic cursor for incremental sync. Advanced on insert and on every
    # content-changing update (status flips, edits), but never on stats-only
    # updates (hit_count/last_hit_at) so popular fingerprints don't churn sync.
    op.execute("CREATE SEQUENCE IF NOT EXISTS fingerprints_sync_seq")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS fingerprints (
            id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sync_seq               BIGINT NOT NULL DEFAULT nextval('fingerprints_sync_seq'),
            phash_hex              TEXT NOT NULL,
            algorithm              TEXT NOT NULL DEFAULT 'phash',
            algorithm_version      TEXT NOT NULL DEFAULT 'imagehash.phash',
            normalization_version  TEXT NOT NULL DEFAULT 'alpha_white_v1',
            category               TEXT NOT NULL,
            action                 TEXT NOT NULL,
            consumer_id            BIGINT NOT NULL REFERENCES consumers(id),
            source_guild_id        TEXT,
            reason                 TEXT,
            source_url             TEXT,
            added_at_ms            BIGINT NOT NULL,
            updated_at_ms          BIGINT NOT NULL,
            hit_count              BIGINT NOT NULL DEFAULT 0,
            last_hit_at_ms         BIGINT,
            auto_added             BOOLEAN NOT NULL DEFAULT FALSE,
            provenance             TEXT NOT NULL DEFAULT 'manual_staff',
            status                 TEXT NOT NULL DEFAULT 'active',
            flag_count             BIGINT NOT NULL DEFAULT 0,
            CONSTRAINT chk_fingerprints_action
                CHECK (action IN ('kick', 'timeout')),
            CONSTRAINT chk_fingerprints_category
                CHECK (category IN ('scam', 'nsfw', 'crypto', 'phishing', 'other')),
            CONSTRAINT chk_fingerprints_status
                CHECK (status IN ('active', 'hidden', 'deleted')),
            CONSTRAINT chk_fingerprints_hit_count CHECK (hit_count >= 0),
            CONSTRAINT chk_fingerprints_flag_count CHECK (flag_count >= 0),
            CONSTRAINT uq_fingerprints_phash_consumer UNIQUE (phash_hex, consumer_id)
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_fingerprints_sync_seq "
        "ON fingerprints(sync_seq)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fingerprints_phash_hex "
        "ON fingerprints(phash_hex)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fingerprints_category "
        "ON fingerprints(category)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fingerprints_compat "
        "ON fingerprints(algorithm, algorithm_version, normalization_version)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fingerprints_consumer_id "
        "ON fingerprints(consumer_id)"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS fingerprint_hits (
            id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fingerprint_id BIGINT NOT NULL REFERENCES fingerprints(id) ON DELETE CASCADE,
            consumer_id    BIGINT NOT NULL REFERENCES consumers(id),
            guild_id       TEXT,
            distance       INTEGER,
            hit_at_ms      BIGINT NOT NULL
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fingerprint_hits_fingerprint_id "
        "ON fingerprint_hits(fingerprint_id)"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS fingerprint_flags (
            id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fingerprint_id BIGINT NOT NULL REFERENCES fingerprints(id) ON DELETE CASCADE,
            consumer_id    BIGINT NOT NULL REFERENCES consumers(id),
            reason         TEXT,
            created_at_ms  BIGINT NOT NULL,
            CONSTRAINT uq_fingerprint_flags UNIQUE (fingerprint_id, consumer_id)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_fingerprint_flags_fingerprint_id "
        "ON fingerprint_flags(fingerprint_id)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fingerprint_flags")
    op.execute("DROP TABLE IF EXISTS fingerprint_hits")
    op.execute("DROP TABLE IF EXISTS fingerprints")
    op.execute("DROP SEQUENCE IF EXISTS fingerprints_sync_seq")
    op.execute("DROP TABLE IF EXISTS consumers")
